# Generated by Django 4.1.3 on 2022-12-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0002_remove_categories_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='malls',
            field=models.ManyToManyField(to='find_mall_api.mall'),
        ),
    ]
