# Generated by Django 4.1.3 on 2022-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0003_alter_mall_created_at_alter_mall_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
