# Generated by Django 4.1.5 on 2023-01-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0004_tag_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_mall_api.categories'),
        ),
    ]
