# Generated by Django 4.1.3 on 2022-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='mall_id',
            field=models.BigIntegerField(),
        ),
    ]
