# Generated by Django 4.1.5 on 2023-01-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0006_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Projects/Web/find-mall-backend/src/image_download/'),
        ),
    ]
