# Generated by Django 4.1.3 on 2022-12-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0006_alter_item_category_id_alter_item_mall_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mall_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_mall_api.categories'),
        ),
    ]
