# Generated by Django 4.1.3 on 2022-12-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0007_remove_item_mall_id_alter_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
