# Generated by Django 4.1.5 on 2023-02-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0009_alter_categories_id_alter_item_id_alter_mall_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_mall_api.item')),
            ],
        ),
    ]
