# Generated by Django 4.1.5 on 2023-02-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_mall_api', '0010_othertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertag',
            name='location',
        ),
    ]
